sudo: false
language: node_js
node_js: 
- 10.15.0
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm run test-single
after_success: npm run coverage
deploy:
  provider: heroku
  api_key: 0b7f3950-27e6-44ae-97e6-e8a96950b8cd
  app: Banka-project
  on:
    repo: acedeywin/Banka-project
    branch: develop


