sudo: false
language: node_js
node_js: 
- 10.15.0
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm run test-single
after_success: npm run coverage
deploy:
  provider: heroku
  api_key: 1e18feba-bc2f-41d5-84b3-62d28ead1ac9
  app: Banka-project
  on:
    repo: acedeywin/Banka-project
    branch: develop


